services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3033:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - k6-network
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - k6-network

  # chronograf:
  #   image: chronograf:1.8
  #   container_name: chronograf
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=root
  #     - INFLUXDB_PASSWORD=root
  #     - INFLUXDB_SKIP_VERIFY=true
  #   depends_on:
  #     - influxdb
  #   networks:
  #     - k6-network
  k6:
    image: grafana/k6
    container_name: k6
    # depends_on:
    #   - influxdb
    working_dir: /scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      # - K6_OUT=prometheus
    volumes:
      - ./k6:/scripts
      - ./tsconfig.json:/scripts/tsconfig.json
    networks:
      - k6-network

volumes:
  influxdb-data:
  grafana-data:

networks:
  k6-network:
    driver: bridge